### ISSUE TITLE
Indentation in curly brackets is off

### ISSUE THREAD

**Issue by moschlar** [neilhwatson/vim_cf3#45]
Hi,

when I reindent a whole .cf file using `gg=G`, a hanging indent gets applied to all but the first line in curly braces:
```
  "webserver"
    or => {
      "www-01,"
        "www-02",
        "www-03",
```
Do you know how I can prevent this?

Regards,
Moritz

**Comment by neilhwatson** [comment]
This is not related to this plugin. I can reproduce this in a non *.cf file. Ask over at #vim or stackoverflow.

**Comment by moschlar** [comment]
Oh yes, it seems to be because of the "+N" cinoption...
http://vimdoc.sourceforge.net/htmldoc/indent.html#cinoptions-values
